version: "3.8"

services:
  web:
    build: .
    container_name: sukjenogi-backend
    ports:
      - "8000:8000"
#    volumes:
#      - .:/app
    environment:
#      - DATABASE_URL=postgresql://sukje_user:sukje_pass@host.docker.internal:5432/sukjenogi_db
      - DATABASE_URL=postgresql://sukje_user:sukje_pass@192.168.0.70:5432/sukjenogi_db
      - SECRET_KEY=some_really_secret_string
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
volumes:
  postgres_data:
